### PR TITLE
cmake improvements

### PR DESCRIPTION
**Pull request by alonbl**
Allow overriding install directories
Do not build MTM unless requested
Allow disable device build

### CODE REVIEW

**Comment by PeterHuewe** [comment]
Looks good to me - merged

**Comment by alonbl** [comment]
which version of cmake do you use?

**Comment by PeterHuewe** [comment]
$ cmake --version
cmake version 3.9.6

**Comment by alonbl** [comment]
same as I, what is the output of:
```
$ cmake -LA .. | grep CMAKE_INSTALL_LIBDIR
CMAKE_INSTALL_LIBDIR:PATH=lib64
```

**Comment by PeterHuewe** [comment]
```
/fast/tpm-emulator $ cmake -LA .. | grep CMAKE_INSTALL_LIBDIR
CMake Error: The source directory "/fast" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

```
$ cd build
/fast/tpm-emulator/build $ cmake -LA .. | grep CMAKE_INSTALL_LIBDIR
CMake Error at CMakeLists.txt:19 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "tddl".


CMake Error at CMakeLists.txt:20 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "tddl_static".


CMake Error at CMakeLists.txt:21 (install):
  install FILES given no DESTINATION!

```

**Comment by PeterHuewe** [comment]
sorry, please ignore - I had to delete the cmake cache first.

**Comment by alonbl** [comment]
I can reproduce this if I remove the following from CMakeLists.txt:
```
include(GNUInstallDirs)
```

This is workaround:
```
cmake -DCMAKE_INSTALL_LIBDIR=lib64 -DCMAKE_INSTALL_BINDIR=bin -DCMAKE_INSTALL_INCLUDEDIR=include ..
```

Need to understand why it is not included for you, searching.

**Comment by alonbl** [comment]
oh... everything is ok?

**Comment by PeterHuewe** [comment]
Yes - everything okay.

**Pull request merged**
