### PR TITLE
Use stable kernel api for userspace socket communication

### PR DESCRIPTION
**Pull request by quitschbo**
This patch replaces calls to sock_sendmsg and sock_recvmsg
to the corresponding kernel_sendmsg and kernel_recvmsg functions.
Those functions were introduced in kernel 2.6.8 and have not
changed till 4.9. This sould provide compatibility to all current
kernels also any problems introduced lately in 4.7 which changed
the prototyp of sock_recvmsg().

### CODE REVIEW

**Comment by langbeck** [comment]
I tested this patch in a Debian stretch with kernel 4.9.0-1-amd64 and confirm that this patch solves the problem described in #14

**Comment by theopolis** [comment]
On a Ubuntu 4.8.0 kernel:
```
[  654.477142]  fjes [last unloaded: tpmd_dev]
[  654.477150] CPU: 0 PID: 6404 Comm: qemu-system-arm Tainted: G           OE   4.8.0-34-generic #36-Ubuntu
[  654.477169] Hardware name: System manufacturer System Product Name/Z170, BIOS 12
[  654.477187] task: ffff983775060f00 task.stack: ffff983761d28000
[  654.477201] RIP: 0010:[<ffffffffaac3f516>]  [<ffffffffaac3f516>] memcpy_erms+0x6/0x10
[  654.477218] RSP: 0018:ffff983761d2bc30  EFLAGS: 00010206
[  654.477230] RAX: ffff98384da51600 RBX: 000000000000000a RCX: 000000000000000a
[  654.477245] RDX: 000000000000000a RSI: 00007fffdb078370 RDI: ffff98384da51600
[  654.477259] RBP: ffff983761d2bc88 R08: 00000000000000c0 R09: ffff983865c7db80
[  654.477275] R10: ffff98384da3bf00 R11: ffff98384da51600 R12: ffff983761d2be08
[  654.477289] R13: ffff98384da5160a R14: 000000000000000a R15: ffff983761d2bde8
[  654.477305] FS:  00007f9af1f45c40(0000) GS:ffff98388bc00000(0000) knlGS:0000000000000000
[  654.477328] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  654.477341] CR2: 00007fffdb078370 CR3: 0000000721ce8000 CR4: 00000000003406f0
[  654.477356] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[  654.477370] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[  654.477385] Stack:
[  654.477391]  ffffffffaac462cd ffff983775060f00 ffff983775060f00 ffff983761d2bca8
[  654.477409]  ffff983775060f00 000000000000000a 000000000000000a 000000000000000a
[  654.477428]  000000000000000a 0000000000000000 000000000000000a ffff983761d2bce8
[  654.477445] Call Trace:
[  654.477455]  [<ffffffffaac462cd>] ? copy_from_iter+0x12d/0x340
[  654.477470]  [<ffffffffaaf71a38>] skb_copy_datagram_from_iter+0x58/0x200
[  654.477495]  [<ffffffffab02aed8>] unix_stream_sendmsg+0x188/0x400
[  654.477509]  [<ffffffffaaf61a88>] sock_sendmsg+0x38/0x50
[  654.477522]  [<ffffffffaaf61bbb>] kernel_sendmsg+0x2b/0x30
[  654.477535]  [<ffffffffc0a190cc>] tpmd_handle_command+0x5c/0x170 [tpmd_dev]
[  654.477550]  [<ffffffffc0a19231>] tpm_write+0x51/0x80 [tpmd_dev]
[  654.477571]  [<ffffffffaaa333d8>] __vfs_write+0x18/0x40
[  654.477583]  [<ffffffffaaa33b15>] vfs_write+0xb5/0x1a0
[  654.477595]  [<ffffffffaaa34f65>] SyS_write+0x55/0xc0
[  654.477607]  [<ffffffffaa803b9e>] do_syscall_64+0x5e/0xc0
[  654.477620]  [<ffffffffab09c365>] entry_SYSCALL64_slow_path+0x25/0x25
[  654.477634] Code: 90 90 90 90 90 eb 1e 0f 1f 00 48 89 f8 48 89 d1 48 c1 e9 03 83 e2 07 f3 48 a5 89 d1 f3 a4 c3 66 0f 1f 44 00 00 48 89 f8 48 89 d1 <f3> a4 c3 0f 1f 80 00 00 00 00 48 89 f8 48 83 fa 20 72 7e 40 38 
[  654.477725] RIP  [<ffffffffaac3f516>] memcpy_erms+0x6/0x10
[  654.477741]  RSP <ffff983761d2bc30>
[  654.477750] CR2: 00007fffdb078370
[  654.482914] ---[ end trace 7a3f6ec6d2ad018a ]---
```

Seems I can trigger with:
```
$ sudo ./build/tpmd/unix/tpmd -f
```

And `0x80 0x01 0x00 0x00 0x00 0x0a 0x00 0x00 0x01 0x81`

**Comment by xrayn** [comment]
Works. Tested with Linux 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2 (2017-06-12) x86_64 GNU/Linux on recent Debian 9 release.

**Comment by PeterHuewe** [comment]
@theopolis Hi can you test whether this is a regression with this patch or whether this is something new?

**Pull request merged**
